### ISSUE TITLE
[Mod Incompat] Doesn't work properly with Origins Classes

### ISSUE THREAD

**Issue by ConqAra** [avetharun/OriginalFur#1]
Tested with [Origins Classes](https://modrinth.com/mod/origins-classes) and it seems most of the furs on the player model do not work properly and bug out.

I posted a few examples below

**Comment by ConqAra** [comment]
![image](https://github.com/avetharun/OriginalFur/assets/76233356/69860bb4-312a-4823-bf3a-0f96d2575caf)
Shulk

**Comment by ConqAra** [comment]
![image](https://github.com/avetharun/OriginalFur/assets/76233356/e2e23a2e-fd94-40d2-9431-7b25a3d60317)
Blazeborn

**Comment by avetharun** [comment]
Sorry for the late response! Working on this now. Thank you!

**Comment by avetharun** [comment]
Should be fixed as of [1.0.2](https://modrinth.com/mod/origin-furs/version/1.0.2). If any further issues occur, please create another issue!
