### ISSUE TITLE
permission to make these into figura avatars?

### ISSUE THREAD

**Issue by akirapink** [avetharun/OriginalFur#16]
so, some friends of mine wanted to use this mod, but we also use figura. and origins minus.
it seems like it'd be super easy to convert them to figura avatars instead with how the models are bbmodels, but i was advised to ask for permission first before doing that, so this is that!
i will not be posting those in the figura server, though!

**Comment by avetharun** [comment]
Go ahead

**Comment by avetharun** [comment]
Closing, also you are welcome to post the models anywhere, or use them however❤️
