### ISSUE TITLE
[Idea/Suggestions] TooManyOrigins Furs

### ISSUE THREAD

**Issue by ConqAra** [avetharun/OriginalFur#2]
[TooManyOrigins](https://modrinth.com/mod/toomanyorigins) is my favorite Origins add-on mod, so I would like to provide idea/suggestions as for the furs of those. It doesn't have to be listened to but hey I wanted to tell you cuz why not!
Withered: Maybe withered parts on half of the body? Would seem cool I think.
Undead: Have part or some of the body as rotten green parts like a zombie. Legs, Arms, etc.
DragonBorn: Dragon Scales incorporated into the body and maybe even a ender dragon tail similar to the merling!
Hare: Rabbit ears and Feet! 
Swarm: Small bee wings on the back, and their little antennas sticking out of the head!
Hiss-kin: Unsure for this one, maybe textures of a creeper similar to what you did with the shulk origin and have TNT in the middle / where the heart is, or TNT/dynamite patches on the character model?

**Comment by avetharun** [comment]
That's on the list, but I'll work with these!
