### ISSUE TITLE
unable to register custom origins in additional filepaths

### ISSUE THREAD

**Issue by BaconPalm** [avetharun/OriginalFur#6]
Finally got round to making custom models for my origins, and found this small thing with file pathing;

if the origin .json isn't located in the base "origins" path it doesn't register when you make a "namespace.origin.json" in the fur directory.
I may be doing something wrong but I'd thought I'd flag this anyways, since I can't seem to find a workaround for this to work as I want it to.

here's my example for it using my mod, I use directories to help organise my origins as I've got around 30 base origins in it (and not even counting the archetypes for each one on top of that) ;-; 
![image](https://github.com/avetharun/OriginalFur/assets/34732532/b3b796dc-29ac-4c52-9bfb-d304c2326b13)
![image](https://github.com/avetharun/OriginalFur/assets/34732532/9f2abde6-d103-49d4-abbb-3da2c312510a)
This won't register the "roiraces.elf.json" in the furs directory, even if I add .impact1 to it

Moving elf.json to "origins" works and makes the model work in game, which is my fix for now, but it would be nice to able to use my additional directories to keep my workspace organised

**Comment by avetharun** [comment]
If the namespace is different for the origin than the fur it won't work, try making them the same

**Comment by avetharun** [comment]
Actually, if possible send a screenshot or log of the Origins ID so i can see what I can do

**Comment by avetharun** [comment]
(do /data get @s and send the logs)

**Comment by BaconPalm** [comment]
![image](https://github.com/avetharun/OriginalFur/assets/34732532/9aa81747-882a-4baf-bbb7-9f5048806b13)
this is the only thing I can find that's close to an ID

**Comment by avetharun** [comment]
Try making the filename roiraces.impact1/elf.json

**Comment by BaconPalm** [comment]
> Try making the filename roiraces.impact1/elf.json

its not a valid identifier because of the /

**Comment by avetharun** [comment]
Oh, I'll make a new update which will replace the / with another .

**Comment by avetharun** [comment]
I'll make a release to test this, let me know if it works. [Try this version](https://github.com/avetharun/OriginalFur/releases/tag/pre)

**Comment by avetharun** [comment]
The filename should now be roiraces.impact1.elf.json

**Comment by BaconPalm** [comment]
I'm struggling to implement the file into my dev environment (I use intelliJ and the fabric wiki doesn't exactly help with nested Jars) currently using your moderinth maven to implement do you have a direct one for your git?

**Comment by avetharun** [comment]
I don't! let me upload it to modrinth

**Comment by avetharun** [comment]
> I'm struggling to implement the file into my dev environment (I use intelliJ and the fabric wiki doesn't exactly help with nested Jars) currently using your moderinth maven to implement do you have a direct one for your git?

Also, in the future you can use 
modImplementation(files(
            "libs/your.jar"
)) to bundle a mod inside the jar, or you can use a more complicated method and include the jar itself in the META-INF folder of the jar

**Comment by avetharun** [comment]
Please let me know if that build works

**Comment by BaconPalm** [comment]
> Please let me know if that build works

just tried it, it didn't work

**Comment by avetharun** [comment]
Should work properly as of [1.0.6.](https://modrinth.com/mod/origin-furs/version/HNQXlt9L) Reopen this if you encounter any further issues relating to this!

**Comment by BaconPalm** [comment]
Did a quick few tests before sleepi time and still doesn't work from my end fyi. Will attempt again if you've changed anything when I wake up in 10 hours

**Comment by avetharun** [comment]
It's fine! I tested it (the 1.0.6 version) using a similar method to yours, which I will push here and it seemed to work.

**Comment by avetharun** [comment]
This is the method I used for testing it, if it differs from yours let me know https://github.com/avetharun/OriginalFur/tree/master/src/main/resources/data

**Comment by BaconPalm** [comment]
It doesn't differ from mine, however mine still does not work, and I've checked for the typical culprit typos about ten times now so I'm a little stumped ;-;

**Comment by avetharun** [comment]
Could you possibly upload your mod to github so I can see what's wrong & debug it?

**Comment by BaconPalm** [comment]
> Could you possibly upload your mod to github so I can see what's wrong & debug it?

I'll unprivate the current version, forewarning that it'll be a little messy

**Comment by BaconPalm** [comment]
Made it public,

Link here: https://github.com/BaconPalm/Races-of-the-Infinite-1.20.1

**Comment by avetharun** [comment]
I still can't replicate this for some reason. If you find a solution via code make a pull request please
