### ISSUE TITLE
Merling Tail

### ISSUE THREAD

**Issue by UnderneathTheTales** [avetharun/OriginalFur#8]
One of the mods I use chances the Merling model ever so slightly in the water. Thankfully, there are no conflicts between this mod and that one, just only makes the Merling look a little silly while in water. I just wanted to ask if it's possible to have a configurative option that allows the tail from this mod to be visible all the time, while out of water or while in water.
The mod that I was talking about is called the Mermod, just so you know. I don't mind having two tails while in water, but it does look a little silly. I'm just letting you know about it... oh, and just so you know: It doesn't help those who gets hurt from the water, so yay?

**Comment by avetharun** [comment]
I'll add compatibility for this in the next update. Thank you for reporting
it!
